### ISSUE TITLE
The issues panel covers the tab bar

### ISSUE THREAD

**Issue by dchakarov** [krzysztofzablocki/LifetimeTracker#11]
Hi, I am trying to use your tool and it's working but once the panel appears, I can no longer switch between my app tabs. Screenshot attached.
![img_c1c4ea14f29e-1](https://user-images.githubusercontent.com/1482285/31027110-ed5a373e-a540-11e7-882e-f83490744577.jpeg)

**Comment by krzysztofzablocki** [comment]
I'm open to changing Dashboard, its separate from tracking and we just have a basic version, any idea how you'd imagine the change so that its not an issue ? if we just move it to top it will probably be the same but with nav bars?

**Comment by stephengazzard** [comment]
Just encountered this as well. @krzysztofzablocki have you ever used Flex? https://github.com/Flipboard/FLEX In my mind, I want this to work just like their debug toolbar

**Comment by krzysztofzablocki** [comment]
I don't think you need moveable toolbar though, if we put it in top over status bar that shouldn't bother too many people, but I'm open to that

Either of you would like to contribute PR for that ?

**Comment by stephengazzard** [comment]
@krzysztofzablocki I made it movable in a PR - let me know what you think. My concern with putting it in the top is there's gonna be some app that wants to see this and they'll be out of luck. This way it can be moved to wherever it has the least impact at run time.

**Comment by krzysztofzablocki** [comment]
Fixed in 1.0.6
