### ISSUE TITLE
Comparison with FBRetainCycleDetector

### ISSUE THREAD

**Issue by michaeleisel** [krzysztofzablocki/LifetimeTracker#13]
It would be great to see a comparison with FBRetainCycleDetector and other similar libraries if they exist. Otherwise, it raises questions for people looking at the repo like, "did this person investigate other options before releasing this library?", "Can I integrate alongside the other library?" etc.

**Comment by krzysztofzablocki** [comment]
Well if you know how FB tool works then the description would make it obvious as we just track lifetime here and not deal with runtime magic to try to figure out the ptr cycles, and so this can be used with pure swift classes etc but fair point
