### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by Xukazu** [krzysztofzablocki/LifetimeTracker#15]
When fetch repo with Carthage, there is no `LifetimeTrackerDashboardIntegration` class

**Comment by krzysztofzablocki** [comment]
That should not be the case in newer releases? it was an issue in initial one but not for a while

**Comment by krzysztofzablocki** [comment]
let me know if it still happens and I'll reopen it

**Comment by Xukazu** [comment]
Ok, I will try to check it today.

Greetings
Rafał Prążyński
