### ISSUE TITLE
Unable to find a specification for `LifetimeTracker`

### ISSUE THREAD

**Issue by rishabdutta** [krzysztofzablocki/LifetimeTracker#17]
I added the `pod 'LifetimeTracker'` in Podfile.
Upon hitting _pod install_ command it says **Unable to find a specification for `LifetimeTracker`**

What is the issue here?

**Comment by mrxuanzhang** [comment]
I have the same issue

**Comment by isacjoseph2006** [comment]
Same for me

**Comment by oferRounds** [comment]
+1

**Comment by krzysztofzablocki** [comment]
Did you run `pod repo update` before? Cocoapods has not been auto updating repo specs for a while

**Comment by rishabdutta** [comment]
Thanks. That worked.
