### ISSUE TITLE
Build Failed when try to install with carthage 

### ISSUE THREAD

**Issue by amine2233** [krzysztofzablocki/LifetimeTracker#26]
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/amine/Projets/Test/ios-wifi-connect/Carthage/Checkouts/LifetimeTracker/LifetimeTracker.xcodeproj -scheme LifetimeTracker-iOS -configuration Release -derivedDataPath /Users/amine/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/LifetimeTracker/1.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/amine/Projets/Test/ios-wifi-connect/Carthage/Checkouts/LifetimeTracker)

**Comment by krzysztofzablocki** [comment]
Xcode version?

**Comment by amine2233** [comment]
Xcode 9.1 and Swift 4, thanks

**Comment by jcislinsky** [comment]
Hi, Krzysztof and Amine,
that is because tag 1.2 miss some files. Current master works like a charm so it will be sufficiet to tag new version in master.

As a workaround could be used this Carthage configuration
`github "krzysztofzablocki/LifetimeTracker" "master"`

**Comment by krzysztofzablocki** [comment]
good spot @jcislinsky 👍 pushed 1.2.1 that should fix it

**Comment by amine2233** [comment]
👍
