### ISSUE TITLE
Type 'LifetimeTrackerDashboardIntegration' has no member 'visibleWithIssuesDetected'

### ISSUE THREAD

**Issue by Monserg** [krzysztofzablocki/LifetimeTracker#33]
Hi, today I find this article:
http://merowing.info/2017/10/how-to-find-retain-cycles-and-memory-leaks-sooner/
Add pod to my current project (Swift 4, iOS 10.0, Xcode 9.2).
Add code line in AppDelegate func didFinishLaunchingWithOptions.
And receive next error warning (screenshot in attach).
How I can fix it?
Thanks.
<img width="1438" alt="2018-01-25 15 33 10" src="https://user-images.githubusercontent.com/3746830/35392513-cff6cbb0-01ea-11e8-9512-5bd898feb17a.png">

**Comment by krzysztofzablocki** [comment]
hey, what version of the pod are you using?

**Comment by Monserg** [comment]
1.4.0.beta.1

**Comment by Monserg** [comment]
it's ok: now install cocoapods version 1.4.0, change to 'pod 'LifetimeTracker', '~> 1.3'' & modify to
#if DEBUG
            LifetimeTracker.setup(onUpdate: LifetimeTrackerDashboardIntegration.visibleWhenIssueDetected().refreshUI)
#endif
Thanks.
