### ISSUE TITLE
Ambiguous use of 'filter' error.

### ISSUE THREAD

**Issue by cmilr** [krzysztofzablocki/LifetimeTracker#39]
I'm getting an "Ambiguous use of filter" error in _**LifetimeTracker+DashboardView.swift**_.

Any ideas?

I'm running:
Mac OS X 10.12.6
Xcode 9.2
Build version 9C40b

<img width="671" alt="screen shot 2018-03-10 at 4 43 36 pm" src="https://user-images.githubusercontent.com/2286876/37248268-55053e7c-2482-11e8-876e-3b97f1c64f40.png">

**Comment by krzysztofzablocki** [comment]
you have to be on old version of code because we fixed this already https://github.com/krzysztofzablocki/LifetimeTracker/pull/25

**Comment by cmilr** [comment]
Weird. I just installed it for the first time today, via Cocoapods, and
used the instructions from the README.

**Comment by cmilr** [comment]
I went ahead and updated Cocoapods itself, and then reinstalled LifetimeTracker following the instructions in the README, but still got a bunch of errors. Just a friendly FYI.

**Comment by krzysztofzablocki** [comment]
What's the version of the pod it fetched?

**Comment by cmilr** [comment]
Installing LifetimeTracker (1.3.3)

And here's an error I get in my project.


​
