### ISSUE TITLE
Dashboard doesn't show

### ISSUE THREAD

**Issue by FujunLiu** [krzysztofzablocki/LifetimeTracker#43]
I have two questions:
1. There is no way to set the bar or circular style of `LifetimeTrackerDashboardIntegration`
2. I add the code below into the `AppDelegate(didFinishLaunchingWithOptions:)`, but nothing shows and no windows or views related have been added to my view hierarchy.
```
#if DEBUG
	LifetimeTracker.setup(onUpdate: LifetimeTrackerDashboardIntegration(visibility: .alwaysVisible).refreshUI)
#endif
```

Please check that, Thanks.

**Comment by tschob** [comment]
@FujunLiu 

Regarding question 1: Are you using version 1.4.0? `LifetimeTrackerDashboardIntegration` has a new parameter `style` which uses `bar` per default.

You should be able to use `LifetimeTrackerDashboardIntegration(visibility: .alwaysVisible, style: .circular)`

Regarding question 2: Is your scheme set to build Debug (not Release) and do your build settings add the Flag `DEBUG`?

**Comment by FujunLiu** [comment]
I updated to version 1.4.0, and question1 is solved.
But question2 is still there. I'm sure the setup code is executed in my AppDelegate.

And with version 1.4.0, there are two errors in `CircularDashboardViewController` indicating that `toolbarPanned` and `showPopover` function should add `@objc` to be exposed to Objective-C.

**Comment by FujunLiu** [comment]
I think I know why there is nothing shows. There must be any type conforming `LifetimeTrackable` to make it work.

Thanks, you can close this issue.
