### ISSUE TITLE
ViewController has called deinit, but still in couting.

### ISSUE THREAD

**Issue by libern** [krzysztofzablocki/LifetimeTracker#57]
I have an VC, let say A.

```
Root > push > A > then back (this works fine.)
```

However

```
Root > push > A > push B > back to A > back to Root
```

the deinit is called at the end.

but the counting is not getting it right.

**Comment by krzysztofzablocki** [comment]
can you share a sample project that reproduces it?

**Comment by libern** [comment]
Here is the project:
[https://github.com/libern/SampleChiken](https://github.com/libern/SampleChiken)

====
Follow the steps:
1. run project
2. just tap the third tab
3. tap the "button" in the third tab

![image](https://user-images.githubusercontent.com/1830640/58924964-63b2d380-8778-11e9-8bd0-72cb90a3fb84.png)

4. tap the "button" in the new view controller

![image](https://user-images.githubusercontent.com/1830640/58924979-6e6d6880-8778-11e9-8649-546a6ffe2e55.png)

5. you will see a red view controller, then, you just back to the home screen where the three tab controllers are.

6. repeat from 3rd step until you see like above.

**Comment by libern** [comment]
Even through, it should always be 2 leaks, when step 3 is done. However, the leaks are getting bigger.

**Comment by ReneLindhorst** [comment]
@libern I think it is because you are using a `static var lifetimeConfiguration` in your `CommonViewController`. LifetimeTracker will override the `pointerString` of the shared configuration and hence can't properly remove the tracked instance in its `onDealloc`. Doing Step 1 to 5 basically looks like this:
> LifetimeTracker track instance 0x00007fb6f5c2ffe0
> LifetimeTracker track instance 0x00007fb6f5c48220
> LifetimeTracker onDealloc untrack instance 0x00007fb6f5c48220
> LifetimeTracker onDealloc untrack instance 0x00007fb6f5c48220

You could change to a `class var`
  ```
  class var lifetimeConfiguration: LifetimeConfiguration {
        return LifetimeConfiguration(maxCount: 1, groupName: "CommonViewController")
    }
```
and then it "works":
> LifetimeTracker track instance 0x00007fc67142cbb0
> LifetimeTracker track instance 0x00007fc671608690
> LifetimeTracker onDealloc untrack instance 0x00007fc671608690
> LifetimeTracker onDealloc untrack instance 0x00007fc67142cbb0

@krzysztofzablocki I guess you would have the same "problem" in your example if you have more then one instance of `ViewController` which get deallocated. Or am I missing something?

**Comment by libern** [comment]
But according to the guide in readme:

https://github.com/krzysztofzablocki/LifetimeTracker#tracking-key-actors

it suggested static there.

@krzysztofzablocki @ReneLindhorst

**Comment by jcislinsky** [comment]
ReneLindhorst's solution works for me. I also saw deallocated instances.

**Comment by krzysztofzablocki** [comment]
yeah sounds about right, when I originally built this there was no concept of pointer string so there wasn't an override
