### ISSUE TITLE
xcode 11 lifetimeTracker does not work 

### ISSUE THREAD

**Issue by lotawei** [krzysztofzablocki/LifetimeTracker#64]

**Comment by lotawei** [comment]
create  new project   use swift  
pod  init   
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'NiJitest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'LifetimeTracker'
  # Pods for NiJitest

end
pod install
appdelegate            
LifetimeTracker.setup(onUpdate: LifetimeTrackerDashboardIntegration(visibility: .alwaysVisible, style: .circular).refreshUI)
Viewcontroller 
class ViewController: UIViewController,LifetimeTrackable{
   static var lifetimeConfiguration = LifetimeConfiguration(maxCount: +1, groupName: "BASEVC")
    
    // MARK: - Initialization

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)

        self.trackLifetime()

    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)

        self.trackLifetime()
    }
}
can  not  see any  tool view  in viewcontroller  , Is there any problems ?  thank you

**Comment by jazminebarroga** [comment]
By any chance are you testing on iOS 13.5? I have noticed it's not working on that iOS version.

**Comment by krzysztofzablocki** [comment]
released new version that should fix this
