### ISSUE TITLE
Real support for SwiftPackageManager

### ISSUE THREAD

**Issue by lecniers** [krzysztofzablocki/LifetimeTracker#65]
I tried to integrate the library using SwiftPackageManager and it fails, from just browsing the Sources I notices the library uses storyboards and xib files, only the XCode 12 beta supports packages with assets. How this library can support SPM then? 
Thank You for your help in advance, I can't use the Carthage package because it fails to compile with the new XCode 12 beta versions:
- Build version 12A6163b

**Comment by krzysztofzablocki** [comment]
Only logic part of the framework was ever supported by SPM, meaning you'd have tracking abilities and could log leaks etc but not visual aspect of it

**Comment by simonmoser-bluesource** [comment]
Any update on this? We are switching to SPM and loosing LifetimeTracker would be a shame :worried:

**Comment by ltsuchiya** [comment]
I just ran into this as well so I made a PR https://github.com/krzysztofzablocki/LifetimeTracker/pull/74

**Comment by krzysztofzablocki** [comment]
🙇
