### ISSUE TITLE
Adding ability to control red/green colors to make it more accessibility-friendly

### ISSUE THREAD

**Issue by acosmicflamingo** [krzysztofzablocki/LifetimeTracker#76]
LifetimeTracker is brilliant! I love it :)

One small suggestion I'd make is to make it possible for a developer to change the tint color of the text. This would be beneficial for developers who are a bit more visually impaired (so they can pick a green with their ideal contrast ratio), and for those who have red-green color blindness.

Just a small suggestion! Keep it up 🥇

**Comment by krzysztofzablocki** [comment]
good idea, I'd be happy to accept a pr with that improvement :)

**Comment by acosmicflamingo** [comment]
PR with update has been merged. Closing.
