### ISSUE TITLE
SwiftUIApp...

### ISSUE THREAD

**Issue by pjcau** [krzysztofzablocki/LifetimeTracker#78]
Hi, 

I tried to use that in SwiftUI with SwiftUIApp. I use like you told before in `readme.md` with ...willConnect and integration with WindowGroup...like this screenshots...but I didn't' t see anythings on app.

<img width="930" alt="Screenshot 2022-04-08 at 11 25 32" src="https://user-images.githubusercontent.com/1088176/162408449-c797efe1-f5b3-41c7-ab35-963886063f19.png">

Can you help me ?
Thank for all job in Swift Open Community

**Comment by skywalkerlw** [comment]
same for me

**Comment by krzysztofzablocki** [comment]
There was initial showing bug that I just fixed in 1.8.2
