### ISSUE TITLE
Compiler errors on Swift 4 project

### ISSUE THREAD

**Issue by MihaiPantiru** [krzysztofzablocki/LifetimeTracker#8]
Installing LifetimeTracker using Cocoapods on a Swift 4 project ended up with 3 compiler errors:

![125b5eb6-b4a1-44bf-88ed-aefdd4e08b8a](https://user-images.githubusercontent.com/481425/31007781-f27b7aa0-a501-11e7-96b4-7e29e669d8ac.png)

**Comment by krzysztofzablocki** [comment]
I released 1.0.4 that fixes it 👍
