### ISSUE TITLE
Release 1.8.1 on CocoaPods or add a note in the Readme that CocoaPods is no longer available

### ISSUE THREAD

**Issue by Lutzifer** [krzysztofzablocki/LifetimeTracker#81]
As I stumbled upon it myself:

Is CocoaPods still supported for this lib? I wondered why I did not find the onLeakDetected initialiser when using CocoaPods and found, that the newest version is not available. Might be worth a note in the Readme.

**Comment by krzysztofzablocki** [comment]
pushed

**Comment by Lutzifer** [comment]
thanks!
