### ISSUE TITLE
Dashboard never appears (both .bar and .circular)

### ISSUE THREAD

**Issue by eunbijang** [krzysztofzablocki/LifetimeTracker#89]
Hi. I've been faced with a issue.

**Xcode Version - 14.3
Swift Language Version - Swift 5
LifetimeTracker Version - 1.8.0 (Swift Package Manager)**

**_In SceneDelegate file,_**
`#if DEBUG LifetimeTracker.setup(onUpdate: LifetimeTrackerDashboardIntegration(visibility: .alwaysVisible, style: .circular).refreshUI) #endif`

**_In ViewController file,_**

```
class HomeViewController: UIViewController, LifetimeTrackable {

   static var lifetimeConfiguration: LifetimeConfiguration {
        return LifetimeConfiguration(maxCount: 1, groupName: "VC")
    }

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        trackLifetime()
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
        trackLifetime()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // ... //
    }
}
```

Dashboard view never appears 😢
I need some help.

**Comment by krzysztofzablocki** [comment]
There was initial showing bug that I just fixed in 1.8.2
