### ISSUE TITLE
How to include LifetimeTracker only in debug builds?

### ISSUE THREAD

**Issue by Nooba** [krzysztofzablocki/LifetimeTracker#95]
Hello,

It may be that I’m missing something simple, but with the new Privacy declaration from Apple, it occurred to me that we are including LifetimeTracker in our current Release builds. It’s not a huge problem, since the relevant function calls are disabled, but still.
Do you know of any way to easily prevent including the library in these Release builds?
We use it as an SPM dependency.

Thanks!

**Comment by krzysztofzablocki** [comment]
Most folks have it even enabled in prod, just don't connect the UI function and instead connect things like sentry to automatically report leaks.

If you wanted to exclude modules from debug builds you'd probably need to create a normal xcode framework and import them there and only enable it in debug builds
