### ISSUE TITLE
LifetimeTrackable

### ISSUE THREAD

**Issue by bukira** [krzysztofzablocki/LifetimeTracker#96]
does this ONLY work with LifetimeTrackable? in a class?

Doesnt track any memory Leakes from anything not supporting LifetimeTrackable?

**Comment by krzysztofzablocki** [comment]
You need to conform to protocol and specify the configuration otherwise there is no logic to perform to check if it's breaking rules

**Comment by bukira** [comment]
ok thxs, not much use to me then, could do that myself :-) but great work,
